name: Deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      
      - name: Create site
        run: |
          mkdir _site
          cat > _site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <meta name="google-site-verification" content="8mgfGaygq4UR_VDn7O_O6MhFYS9CaBpkEG1ONsKoG3M" />
              <title>Keycloak Email OTP Provider</title>
              <style>
                  body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
                  a { color: #0366d6; margin-right: 20px; }
              </style>
          </head>
          <body>
            <h1>Keycloak Email OTP Provider</h1>
            <a href="https://github.com/RalfsVetra/keycloak-email-otp-provider">Repository</a>
            <br>
            <a href="https://github.com/RalfsVetra">Author</a>
          </body>
          </html>
          EOF
          echo 'google-site-verification: 8mgfGaygq4UR_VDn7O_O6MhFYS9CaBpkEG1ONsKoG3M' > _site/google8mgfGaygq4UR_VDn7O_O6MhFYS9CaBpkEG1ONsKoG3M.html
          touch _site/.nojekyll
      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
      - uses: actions/deploy-pages@v4
        id: deployment
